import styles from "./AddOption.module.css";

export const AddOption = (props: string) => {
  return (
    <>
      {props.optionNumber === "1" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "2" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "3" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "4" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "5" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "6" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "7" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "8" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "9" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "10" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "11" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
      {props.optionNumber === "12" && (
        <>
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />

          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
          <input
            type="text"
            placeholder="option"
            className={styles["input-field"]}
            required
          />
        </>
      )}
    </>
  );
};
